### PR TITLE
Settings revamp + viewmodel

### PR DESCRIPTION
**Pull request by tboby**
### What did you fix? (provide a description or issue closes statement)

This reworks the settings save/load code to use implicit json serialization.
It also add a viewmodel for the Settings window and removes a lot of direct event methods, replacing them with attached properties (e.g. the numeric only), value converters (the negative offset y), and inline processing in the viewmodel setters.
Finally it adds a readonly settings model that is used by anywhere that doesn't need to edit settings, slowly moving away from the static Settings class.

It also adds a scrollbar to the settings window along with a vertical resize handle, plus makes the scrollbar a bit wider.

---

### Considerations
- Does this contain a new dependency? **[Yes]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

### CODE REVIEW

**Comment by tboby** [comment]
@dapal-003 Replying here as the new scrollbar is in this MR.

> Very interesting. Could you give it a try on high and low resolutions and see if it's still fine under high/low DPI settings in Windows?

It seems to behave as expected with DPI settings. If I ramp DPI up too high on my low res laptop screen it can become difficult to use the whole settings window as I only have 900 height and 594 * 1.5 scaling = 891 which hides behind my taskbar. That'd be an odd thing for a user to do though!

**Comment by dimon222** [comment]
Merge conflict, pls resolve

**Comment by tboby** [comment]
> Merge conflict, pls resolve

Done. Updated the new default values for the two touched settings.

**Comment by dapal-003** [comment]
Sadly some more merge conflicts arose while merging two older branches in, could you please update and resolve the conflicts? Thanks

**Comment by tboby** [comment]
Fixed again!

**Pull request merged**
