### PR TITLE
Overlay Offset in options

### PR DESCRIPTION
**Pull request by saceria**
added ability to adjust the overlays position through an offset option in the settings using the provided sliders or text boxes.

The settings option is contextual and only shows when Overlay is selected.

### CODE REVIEW

**Comment by saceria** [comment]
I tested it as much as I could, but its probable I missed something.

If you happen to be using a 1440p monitor, a y offset of 130 puts the overlay just under the player names.

**Comment by saceria** [comment]
After trying it out on scaled dpi, I've opted to also scale the offset values. I think this makes more sense, as users would expect that the displacement should relatively be the same. Its also easier to manipulate when at higher scaling.

As for language issues pertaining to cultures, I couldn't note any while using the JP and KR packs. I'm not 100% on this being the same for Arabic , Sanskrit, Cyrilic etc, but I note that the other input text boxes in settings also ignore culture formatting, so I assume they're only supposed to take and give back the English numerals.

I'll come back to check again if there's anything else. Otherwise, just more general use testing, and something for the docs.

**Comment by dapal-003** [comment]
I finally had some time to check it out in further details, there are a few regards I'd like to mention. For the UI: 
There is no need to have sliders here, typing a value for an offset is just fine. 
    If the sliders stay, then they will have to be changed so that they increment per 1 step instead of 10. 
Currently the limit on the sliders is 1000 but you can go way over that when entering in a value manually. Adding a check for a value greater than or lower than 1000 would have to be added on-top of the current input detection. 
The text "Restart WFinfo" doesn't need to be there as the changes apply with the next check.
Inverting the values would be helpful too, seeing as it is expected that lower values should bring things down, higher values bring things up.

**Comment by saceria** [comment]
Done. Opted to remove the sliders since I think users would better appreciate the fine tuning that text boxes would bring.
The restart text was my own mistake, since between some of my tests I thought the offset wasn't updating between screens.
Lastly, inverted the Y value where it is facing the user. So it's the correct value for the screen space internally, but the user thinks up is +ve.

**Comment by dapal-003** [comment]
WFInfo_2020-11-09_18-51-42
Looks great 👍, I'm willing to merge it once there's a limiter for these values. Seeing as 1/2 of a 4k screen height is 1080. a maximum of +/-1000 should be sufficient for all cases. If you want to go the extra step you could also change the maximum depending on the game's height. The value is available in the OCR class as `window.height` By default this would not be initiated but if it is then you can use half of it instead of the 1000.

**Comment by saceria** [comment]
I did make it dynamic, with default bounds for -1K : 1K. It should query if warframe is valid, and if so checks if the window has been set, otherwise forces an update itself.

**Comment by dapal-003** [comment]
Seems for some reason this commit never got merged into master?

**Comment by saceria** [comment]
really?

**Comment by saceria** [comment]
I did get the merged notification hmm, I'll submit again

**Comment by saceria** [comment]
I think I'll just let the fork exist in perpetuity this time. Maybe deleting it too soon was the issue. But that's pretty weird. I definitely got the notification that it was fine to delete, and this hasn't happened before :(

**Pull request merged**
