### PR TITLE
Snap-It item counting

### PR DESCRIPTION
**Pull request by D1firehail**
### What did you fix? (provide a description or issue closes statement)
Alternate solution to \#171 - This is a different fix than \#172 mainly to make the bounding boxes symmetrical and less overextended. This also includes switching OCR mode used for Snap-It to `TextLine` (previously `Word`), which seems to improve accuracy with no downsides as far as I can see.

Progress on \#14 - For Prime parts, allows more owned than what's needed for a set. Set progress per part is capped by amount needed for set. Also adds sort options for total parts owned, owned plat value and owned ducat value

Closed \#66 (at least in my interpretation) - Will work out the grid system in the scanned area, with configurable filtering of leftover parts of the item icon and noise. Asks the user to verify that the scanned item names and counts are correct, with options to cancel, backup and clear existing inventory and saving the scanned item counts into inventory. Noise filter aggressiveness and enabling this feature is accessible via the UI, while settings for the removal of item icons is only in the file. Scanned item amount is also included in the csv export.

**Note:** This could all use some more testing on different resolutions and themes, but I'm fairly certain most counting problems can be fixed by playing around with the settings a bit. I also haven't really worked with UI or C# specifically before, so you might want to double check that I'm following naming standards and didn't mess up some part of the UI by accident without noticing.

---

### Reproduction steps

1.  (optional) Run once to generate new settings in file, then edit SnapItEdgeWith and SnapItEdgeRadius to work better with your UI Theme and resolution.
2. Enable "Count Items" in settings
3.  Increase your Display Time setting to have time to verify results
4. Use Snap-It, only the inventory grid for best results.
5. (optional) Click "Backup and clear inventory" to backup and clear equipment inventory
5. Check if scan results are accurate, if not click "Cancel" in the new window and change "Snap Noise" setting and/or settings mentioned in 1. Optionally, try your luck with scanning the area in multiple parts.
6. If scan was accurate, select "Save Count" to insert the item amounts into inventory system.
7. Repeat from step 4 however many times you want.
8. Open Prime Inventory Window and check out your owned parts.
9. Try changing sorting options to "Owned", "Owned Value (Plat)" and/or "Owned Value (Ducats)".

---

### Evidence/screenshot/link to line

SnapItImage 2021-04-29 17-05-1322
SnapItImageFiltered 2021-04-29 17-05-1322
SnapItImageBounds 2021-04-29 17-05-1648
Results

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[No, don't know how]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix and Enhancement]**

### CODE REVIEW

**Comment by D1firehail** [comment]
Realized I should probably add sorting options for amount owned and owned value, so setting this back to draft

**Comment by dapal-003** [comment]
Tested, worked as intended

**Comment by dimon222** [comment]
@dapal-003 what about Korean?

**Comment by dapal-003** [comment]
Tested it with Korean, and it spawned the screen and functioned as expected

**Pull request merged**
